### ISSUE TITLE
Start button in Main Menu breaks menu system

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#45]
### Repro Steps:
1. Start new game
2. Press Start
3. Hit 'A' to start local game
4. Join with both players

### Expected: 
Both players join the game and can select characters

### Actual: 
Players are stuck in the menu

**Comment by Juskelis** [comment]
Cannot reproduce - are you selecting the map with both players? Both players are required to vote before it can continue

**Comment by JXVD** [comment]
Repro'd Feb 7th. With 2 xbox controllers plugged in, hit start on one, then hit a. The game will advance to the character select, but will never register that two players have hit start.

**Comment by Juskelis** [comment]
Strange, I'm still unable to reproduce this. Make sure that the Min Players to Advance field in Player Select's Multiplayer UI Component is set to 2 on your local version. The GameObject is in Lobby & the full parent path is Lobby Manager -> LobbyPanel -> Main Panel -> Player Select

**Comment by JXVD** [comment]
The UI component has Min. Players to Advance as 2 and the path is correct.
