### ISSUE TITLE
Characters do not bump into each other

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#47]
### Repro Steps
Start a game
run one character into the other

### Expected
Characters bump into and move away from each other

### Actual
Characters do not register the other's presence. Lifeless, unfeeling, living in a solitary world

**Comment by Juskelis** [comment]
Issue comes from synchronization issues. MovementState takes a ref to externalForces, which is assumed to be the true externalForces variable. Player passes a value copy of externalForces instead though, due to the need to control sync events.

**Comment by Juskelis** [comment]
To solve, I'm planning on changing movementstates from taking in ref variables to calling the appropriate update functions in player component as well as move DecayExternalForces out of UpdateState. This will require player to explicitly call it.

**Comment by JXVD** [comment]
Fixed in #54
