### ISSUE TITLE
Bounce Mechanic breaks when done upwards

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#48]
### Repro Steps
1. Start a game
2. Stand one character on top of the other [assuming #47 is not fixed yet]
3. Have the top character dash upwards

### Expected Functionality
Depending on design, either nothing or the bottom character dies

### Actual
The game produces infinite bodies, lagging out forever.

**Comment by JXVD** [comment]
Issue #47 has been fixed, but this is still a bug that is present. New Repro is simply bouncing on top of the other character and timing the upwards dash correctly.

**Comment by Juskelis** [comment]
Does this still fail?

**Comment by JXVD** [comment]
can no longer reproduce
