### ISSUE TITLE
Platforms behave strangely

### ISSUE THREAD

**Issue by Juskelis** [Juskelis/Champloo#55]
### Repro Steps
1. Start a game
2. Place character on top of moving platform

### Expected Functionality
Player follows platform smoothly, both up and down.

### Actual
Player clips through platform if moving up, and does not stick to platform if moving down.

**Comment by Juskelis** [comment]
Similar to #47, this is probably due to a synchronization issue. My guess is that the platform modifies the player's position directly, rather than using proper methods.

**Comment by Juskelis** [comment]
Turns out the issue was not with synchronization like I thought, but instead was because OnGround was doing the Controller2Ds job for it

**Comment by Juskelis** [comment]
The reason for On Ground (and others) doing this is because gravity is applied directly to the velocity. When on ground, the gravity is applied even when there is ground below, resulting in the gravity being around 20 when the player steps off the platform. This then causes the player to drop abnormally quickly off the platform. The current workaround is to set the y velocity to zero when this occurs.

The issue comes from this happening when the platform wants to move the player too. Movement State sets the velocity to zero while expected is non zero. The current plan for fix is to alter how gravity is calculated so that zeroing in state is not needed and can be safely removed.

**Comment by Juskelis** [comment]
After revisiting the issue, while the above is still largely true, much of it was unnecessary. 

Turns out that the platform in scene was misconfigured in a few key ways.
1. Platform was applying only to Ground layer objects
2. Platform uses raycasts to check who to move. The raycasts were spaced out enough that they could "miss" the player
3. Gravity was being applied to the player even in OnGround, resulting in some weirdness.

**Comment by JXVD** [comment]
Looks like it is fixed
