### ISSUE TITLE
Thrown sword sticks to character model

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#57]
### Repro Steps
1. Start a game
2. Jump while moving to the left or right
3. Throw the sword while in the direction you are moving

### Expected functionality
The sword flies until it hits a wall or a player

### Actual functionality
The sword stops in midair close to the character throwing the sword

### Notes
If the sword is hovering to the left or the right, touching a wall on the left or right will cause it get picked up by the player. This bug may not repro every throw, but I was able to get it consistently.

**Comment by Juskelis** [comment]
I get the feeling this might have to do with me changing the layers from Ground to Player. I'll look into it

**Comment by JXVD** [comment]
fixed in some commit
