### ISSUE TITLE
Mouse Hover in menu stops button inputs

### ISSUE THREAD

**Issue by JXVD** [Juskelis/Champloo#59]
### Repro Steps
1. Start the game in unity
2. Put mouse cursor above the start game button
3. Hit A on controller

### Expected
The game goes to player select

### Actual
Nothing happens

**Comment by Juskelis** [comment]
So one way we can handle this is to simply disable mouse UI input altogether. Thoughts?

**Comment by JXVD** [comment]
I don't mind requiring players to have an xbox controller. I'm ok with this.
